server:
  port: 8001
  error:
    include-exception: true
    include-stacktrace: always
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  servlet:
    multipart:
      enabled: true
      maxFileSize: 30Mb
      max-request-size: 50Mb
